In [20]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2044754"

headers = {
"User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, "lxml")

tables = soup.find_all("table")

data = []

for table in tables:
    rows = table.find_all("tr")

    for row in rows[1:]:
        cols = row.find_all(["td","th"])
        cols = [c.get_text(strip=True) for c in cols]

        if len(cols) >= 2:
            data.append(cols)

df = pd.DataFrame(data)

print(df.head())

df.to_csv("../data/raw/seed_varieties_dataset.csv", index=False)

print("Saved: seed_varieties_dataset.csv")

         0     1                        2        3  \
0  CEREALS
1           Rice  CR Dhan 416 (IET 30201)  Variety
2           Rice   CR DHAN 810(IET 30409)  Variety
3           Rice   CR Dhan 108 (IET29052)  Variety
4           Rice      CSR 101 (IET-30827)  Variety

                                                   4  \
0
1  ICAR-National Rice Research Institute,Cuttack,...
2  ICAR- National Rice Research Institute, Cuttac...
3  ICAR-National Rice Research Institute, Cuttack...
4  ICAR-Central Soil Salinity Research Institute,...

                                               5  \
0                                           None
1               West Bengal, Maharashtra,Gujarat
2                     Odisha, West Bengal, Assam
3                                  Odisha, Bihar
4  Uttar Pradesh, Haryana, Tamil Nadu, Karnataka

                                                   6     7
0                                               None  None
1  Suitable forcoastal saline areas,yield 48.97 q...  None
2  Suitable forrainfed shallow low land, yield 42...  None
3  Suitable for earlydirect seeded rainfed condit...  None
4  Suitable for irrigatedalkaline/saline stress a...  None
Saved: seed_varieties_dataset.csv

In [21]:
df

,0,1,2,3,4,5,6,7
0,CEREALS,,,,,None,None,None
1,,Rice,CR Dhan 416 (IET 30201),Variety,"ICAR-National Rice Research Institute,Cuttack,...","West Bengal, Maharashtra,Gujarat","Suitable forcoastal saline areas,yield 48.97 q...",None
2,,Rice,CR DHAN 810(IET 30409),Variety,"ICAR- National Rice Research Institute, Cuttac...","Odisha, West Bengal, Assam","Suitable forrainfed shallow low land, yield 42...",None
3,,Rice,CR Dhan 108 (IET29052),Variety,"ICAR-National Rice Research Institute, Cuttack...","Odisha, Bihar",Suitable for earlydirect seeded rainfed condit...,None
4,,Rice,CSR 101 (IET-30827),Variety,"ICAR-Central Soil Salinity Research Institute,...","Uttar Pradesh, Haryana, Tamil Nadu, Karnataka",Suitable for irrigatedalkaline/saline stress a...,None
...,...,...,...,...,...,...,...,...
371,,Velvet Bean,Arka Dhanvantari,OpenPollinated Variety,ICAR-Indian Institute of Horticultural Researc...,Karnataka,Long duration variety (180-190 days) with non-...,None
372,,Velvet Bean,Arka Daksha,OpenPollinated Variety,ICAR-Indian Institute of Horticultural Researc...,Karnataka,Medium duration variety comes to maturity 150-...,None
373,,Ashwagandha,Arka Ashwagandha,OpenPollinated Variety,ICAR-Indian Institute of Horticultural Researc...,Karnataka,It is pure line selection with high dry root y...,None
374,,Mandukaparni,Arka Prabhavi,OpenPollinated Variety,ICAR-Indian Institute of Horticultural Researc...,Karnataka,It produces 13 tonnes of fresh herb and 2.3 to...,None
375,,,,,,,,

In [22]:
import pandas as pd

df = pd.read_csv("../data/raw/seed_varieties_dataset.csv")

print("Columns:", df.columns)

# forward fill category
df.iloc[:,0] = df.iloc[:,0].ffill()

# drop empty rows
df = df.dropna(how="all")

# clean text
for col in df.columns:
    df[col] = df[col].astype(str).str.replace("\n"," ").str.strip()

df.to_csv("../data/processed/seed_varieties_cleaned.csv", index=False)

print("Cleaned dataset saved")
print(df.head())

Columns: Index(['0', '1', '2', '3', '4', '5', '6', '7'], dtype='object')
Cleaned dataset saved
         0     1                        2        3  \
0  CEREALS   nan                      nan      nan
1  CEREALS  Rice  CR Dhan 416 (IET 30201)  Variety
2  CEREALS  Rice   CR DHAN 810(IET 30409)  Variety
3  CEREALS  Rice   CR Dhan 108 (IET29052)  Variety
4  CEREALS  Rice      CSR 101 (IET-30827)  Variety

                                                   4  \
0                                                nan
1  ICAR-National Rice Research Institute,Cuttack,...
2  ICAR- National Rice Research Institute, Cuttac...
3  ICAR-National Rice Research Institute, Cuttack...
4  ICAR-Central Soil Salinity Research Institute,...

                                               5  \
0                                            nan
1               West Bengal, Maharashtra,Gujarat
2                     Odisha, West Bengal, Assam
3                                  Odisha, Bihar
4  Uttar Pradesh, Haryana, Tamil Nadu, Karnataka

                                                   6    7
0                                                nan  nan
1  Suitable forcoastal saline areas,yield 48.97 q...  nan
2  Suitable forrainfed shallow low land, yield 42...  nan
3  Suitable for earlydirect seeded rainfed condit...  nan
4  Suitable for irrigatedalkaline/saline stress a...  nan

In [23]:
df

,0,1,2,3,4,5,6,7
0,CEREALS,nan,nan,nan,nan,nan,nan,nan
1,CEREALS,Rice,CR Dhan 416 (IET 30201),Variety,"ICAR-National Rice Research Institute,Cuttack,...","West Bengal, Maharashtra,Gujarat","Suitable forcoastal saline areas,yield 48.97 q...",nan
2,CEREALS,Rice,CR DHAN 810(IET 30409),Variety,"ICAR- National Rice Research Institute, Cuttac...","Odisha, West Bengal, Assam","Suitable forrainfed shallow low land, yield 42...",nan
3,CEREALS,Rice,CR Dhan 108 (IET29052),Variety,"ICAR-National Rice Research Institute, Cuttack...","Odisha, Bihar",Suitable for earlydirect seeded rainfed condit...,nan
4,CEREALS,Rice,CSR 101 (IET-30827),Variety,"ICAR-Central Soil Salinity Research Institute,...","Uttar Pradesh, Haryana, Tamil Nadu, Karnataka",Suitable for irrigatedalkaline/saline stress a...,nan
...,...,...,...,...,...,...,...,...
371,Fruits,Velvet Bean,Arka Dhanvantari,OpenPollinated Variety,ICAR-Indian Institute of Horticultural Researc...,Karnataka,Long duration variety (180-190 days) with non-...,nan
372,Fruits,Velvet Bean,Arka Daksha,OpenPollinated Variety,ICAR-Indian Institute of Horticultural Researc...,Karnataka,Medium duration variety comes to maturity 150-...,nan
373,Fruits,Ashwagandha,Arka Ashwagandha,OpenPollinated Variety,ICAR-Indian Institute of Horticultural Researc...,Karnataka,It is pure line selection with high dry root y...,nan
374,Fruits,Mandukaparni,Arka Prabhavi,OpenPollinated Variety,ICAR-Indian Institute of Horticultural Researc...,Karnataka,It produces 13 tonnes of fresh herb and 2.3 to...,nan
375,Fruits,nan,nan,nan,nan,nan,nan,nan

In [24]:
import pandas as pd

df = pd.read_csv("../data/processed/seed_varieties_cleaned.csv")

# forward fill category
df.iloc[:,0] = df.iloc[:,0].ffill()

# remove rows where crop missing
df = df[df.iloc[:,1].notna()]

# remove category only rows
df = df[df.iloc[:,1] != df.iloc[:,0]]

# rename columns properly
df.columns = [
"Category",
"Crop",
"Name of Variety",
"Variety/Hybrid",
"Sponsoring organization",
"State",
"Description",
"Extra"
]

# drop duplicates
df = df.drop_duplicates()

# reset index
df = df.reset_index(drop=True)

df.to_csv("../data/processed/seed_varieties_final.csv", index=False)

print(df.head())
print("Final dataset saved")

  Category  Crop                                    Name of Variety  \
0  CEREALS  Rice                            CR Dhan 416 (IET 30201)
1  CEREALS  Rice                             CR DHAN 810(IET 30409)
2  CEREALS  Rice                             CR Dhan 108 (IET29052)
3  CEREALS  Rice                                CSR 101 (IET-30827)
4  CEREALS  Rice  Swarna PurviDhan 5 IET 29036 (RCPR 68-IR83929-...

            Variety/Hybrid                            Sponsoring organization  \
0                  Variety  ICAR-National Rice Research Institute,Cuttack,...
1                  Variety  ICAR- National Rice Research Institute, Cuttac...
2                  Variety  ICAR-National Rice Research Institute, Cuttack...
3                  Variety  ICAR-Central Soil Salinity Research Institute,...
4  Open Pollinated Variety  ICAR-Research Complex for Eastern Region, Patn...

                                           State  \
0               West Bengal, Maharashtra,Gujarat
1                     Odisha, West Bengal, Assam
2                                  Odisha, Bihar
3  Uttar Pradesh, Haryana, Tamil Nadu, Karnataka
4                  Bihar, West Bengal, Jharkhand

                                         Description  Extra
0  Suitable forcoastal saline areas,yield 48.97 q...    NaN
1  Suitable forrainfed shallow low land, yield 42...    NaN
2  Suitable for earlydirect seeded rainfed condit...    NaN
3  Suitable for irrigatedalkaline/saline stress a...    NaN
4  Suitable fordirect seeded aerobic condition in...    NaN
Final dataset saved

In [25]:
df.head()

,Category,Crop,Name of Variety,Variety/Hybrid,Sponsoring organization,State,Description,Extra
0,CEREALS,Rice,CR Dhan 416 (IET 30201),Variety,"ICAR-National Rice Research Institute,Cuttack,...","West Bengal, Maharashtra,Gujarat","Suitable forcoastal saline areas,yield 48.97 q...",NaN
1,CEREALS,Rice,CR DHAN 810(IET 30409),Variety,"ICAR- National Rice Research Institute, Cuttac...","Odisha, West Bengal, Assam","Suitable forrainfed shallow low land, yield 42...",NaN
2,CEREALS,Rice,CR Dhan 108 (IET29052),Variety,"ICAR-National Rice Research Institute, Cuttack...","Odisha, Bihar",Suitable for earlydirect seeded rainfed condit...,NaN
3,CEREALS,Rice,CSR 101 (IET-30827),Variety,"ICAR-Central Soil Salinity Research Institute,...","Uttar Pradesh, Haryana, Tamil Nadu, Karnataka",Suitable for irrigatedalkaline/saline stress a...,NaN
4,CEREALS,Rice,Swarna PurviDhan 5 IET 29036 (RCPR 68-IR83929-...,Open Pollinated Variety,"ICAR-Research Complex for Eastern Region, Patn...","Bihar, West Bengal, Jharkhand",Suitable fordirect seeded aerobic condition in...,NaN

In [26]:
state_col = "State"

# split multiple states
df[state_col] = df[state_col].astype(str)

df[state_col] = df[state_col].str.replace(" and ", ",")
df[state_col] = df[state_col].str.replace(";", ",")
df[state_col] = df[state_col].str.replace("/", ",")

# split into list
df[state_col] = df[state_col].str.split(",")

# explode rows
df = df.explode(state_col)

# clean whitespace
df[state_col] = df[state_col].str.strip()

# remove empty rows
df = df[df[state_col] != ""]
df = df[df[state_col] != "nan"]

# reset index
df = df.reset_index(drop=True)

# save dataset
df.to_csv("../data/processed/seed_varieties_state_split.csv", index=False)

print("Saved: seed_varieties_state_split.csv")
print(df.head())

Saved: seed_varieties_state_split.csv
  Category  Crop          Name of Variety Variety/Hybrid  \
0  CEREALS  Rice  CR Dhan 416 (IET 30201)        Variety
1  CEREALS  Rice  CR Dhan 416 (IET 30201)        Variety
2  CEREALS  Rice  CR Dhan 416 (IET 30201)        Variety
3  CEREALS  Rice   CR DHAN 810(IET 30409)        Variety
4  CEREALS  Rice   CR DHAN 810(IET 30409)        Variety

                             Sponsoring organization        State  \
0  ICAR-National Rice Research Institute,Cuttack,...  West Bengal
1  ICAR-National Rice Research Institute,Cuttack,...  Maharashtra
2  ICAR-National Rice Research Institute,Cuttack,...      Gujarat
3  ICAR- National Rice Research Institute, Cuttac...       Odisha
4  ICAR- National Rice Research Institute, Cuttac...  West Bengal

                                         Description  Extra
0  Suitable forcoastal saline areas,yield 48.97 q...    NaN
1  Suitable forcoastal saline areas,yield 48.97 q...    NaN
2  Suitable forcoastal saline areas,yield 48.97 q...    NaN
3  Suitable forrainfed shallow low land, yield 42...    NaN
4  Suitable forrainfed shallow low land, yield 42...    NaN

In [27]:
df

,Category,Crop,Name of Variety,Variety/Hybrid,Sponsoring organization,State,Description,Extra
0,CEREALS,Rice,CR Dhan 416 (IET 30201),Variety,"ICAR-National Rice Research Institute,Cuttack,...",West Bengal,"Suitable forcoastal saline areas,yield 48.97 q...",NaN
1,CEREALS,Rice,CR Dhan 416 (IET 30201),Variety,"ICAR-National Rice Research Institute,Cuttack,...",Maharashtra,"Suitable forcoastal saline areas,yield 48.97 q...",NaN
2,CEREALS,Rice,CR Dhan 416 (IET 30201),Variety,"ICAR-National Rice Research Institute,Cuttack,...",Gujarat,"Suitable forcoastal saline areas,yield 48.97 q...",NaN
3,CEREALS,Rice,CR DHAN 810(IET 30409),Variety,"ICAR- National Rice Research Institute, Cuttac...",Odisha,"Suitable forrainfed shallow low land, yield 42...",NaN
4,CEREALS,Rice,CR DHAN 810(IET 30409),Variety,"ICAR- National Rice Research Institute, Cuttac...",West Bengal,"Suitable forrainfed shallow low land, yield 42...",NaN
...,...,...,...,...,...,...,...,...
452,Fruits,Velvet Bean,Arka Dhanvantari,OpenPollinated Variety,ICAR-Indian Institute of Horticultural Researc...,Karnataka,Long duration variety (180-190 days) with non-...,NaN
453,Fruits,Velvet Bean,Arka Daksha,OpenPollinated Variety,ICAR-Indian Institute of Horticultural Researc...,Karnataka,Medium duration variety comes to maturity 150-...,NaN
454,Fruits,Ashwagandha,Arka Ashwagandha,OpenPollinated Variety,ICAR-Indian Institute of Horticultural Researc...,Karnataka,It is pure line selection with high dry root y...,NaN
455,Fruits,Mandukaparni,Arka Prabhavi,OpenPollinated Variety,ICAR-Indian Institute of Horticultural Researc...,Karnataka,It produces 13 tonnes of fresh herb and 2.3 to...,NaN
456,Sr. No.,Crop,Name of the Variety/Hybrid,Variety/ Hybrid,Sponsoring organization,Recommended for the states,Special Features,NaN

In [28]:
df.drop(columns=["Extra"], inplace=True)

In [29]:
df

,Category,Crop,Name of Variety,Variety/Hybrid,Sponsoring organization,State,Description
0,CEREALS,Rice,CR Dhan 416 (IET 30201),Variety,"ICAR-National Rice Research Institute,Cuttack,...",West Bengal,"Suitable forcoastal saline areas,yield 48.97 q..."
1,CEREALS,Rice,CR Dhan 416 (IET 30201),Variety,"ICAR-National Rice Research Institute,Cuttack,...",Maharashtra,"Suitable forcoastal saline areas,yield 48.97 q..."
2,CEREALS,Rice,CR Dhan 416 (IET 30201),Variety,"ICAR-National Rice Research Institute,Cuttack,...",Gujarat,"Suitable forcoastal saline areas,yield 48.97 q..."
3,CEREALS,Rice,CR DHAN 810(IET 30409),Variety,"ICAR- National Rice Research Institute, Cuttac...",Odisha,"Suitable forrainfed shallow low land, yield 42..."
4,CEREALS,Rice,CR DHAN 810(IET 30409),Variety,"ICAR- National Rice Research Institute, Cuttac...",West Bengal,"Suitable forrainfed shallow low land, yield 42..."
...,...,...,...,...,...,...,...
452,Fruits,Velvet Bean,Arka Dhanvantari,OpenPollinated Variety,ICAR-Indian Institute of Horticultural Researc...,Karnataka,Long duration variety (180-190 days) with non-...
453,Fruits,Velvet Bean,Arka Daksha,OpenPollinated Variety,ICAR-Indian Institute of Horticultural Researc...,Karnataka,Medium duration variety comes to maturity 150-...
454,Fruits,Ashwagandha,Arka Ashwagandha,OpenPollinated Variety,ICAR-Indian Institute of Horticultural Researc...,Karnataka,It is pure line selection with high dry root y...
455,Fruits,Mandukaparni,Arka Prabhavi,OpenPollinated Variety,ICAR-Indian Institute of Horticultural Researc...,Karnataka,It produces 13 tonnes of fresh herb and 2.3 to...
456,Sr. No.,Crop,Name of the Variety/Hybrid,Variety/ Hybrid,Sponsoring organization,Recommended for the states,Special Features

In [30]:
def extract_features(text):
    text = str(text).lower()
    
    return pd.Series({
        "drought": int("drought" in text),
        "saline": int("saline" in text),
        "rainfed": int("rainfed" in text),
        "irrigated": int("irrigated" in text),
        "disease_resistant": int("disease" in text),
        "early_maturity": int("early" in text),
        "high_yield": int("high yield" in text)
    })

features = df["Description"].apply(extract_features)

df = pd.concat([df, features], axis=1)

In [31]:
df

,Category,Crop,Name of Variety,Variety/Hybrid,Sponsoring organization,State,Description,drought,saline,rainfed,irrigated,disease_resistant,early_maturity,high_yield
0,CEREALS,Rice,CR Dhan 416 (IET 30201),Variety,"ICAR-National Rice Research Institute,Cuttack,...",West Bengal,"Suitable forcoastal saline areas,yield 48.97 q...",0,1,0,0,1,0,0
1,CEREALS,Rice,CR Dhan 416 (IET 30201),Variety,"ICAR-National Rice Research Institute,Cuttack,...",Maharashtra,"Suitable forcoastal saline areas,yield 48.97 q...",0,1,0,0,1,0,0
2,CEREALS,Rice,CR Dhan 416 (IET 30201),Variety,"ICAR-National Rice Research Institute,Cuttack,...",Gujarat,"Suitable forcoastal saline areas,yield 48.97 q...",0,1,0,0,1,0,0
3,CEREALS,Rice,CR DHAN 810(IET 30409),Variety,"ICAR- National Rice Research Institute, Cuttac...",Odisha,"Suitable forrainfed shallow low land, yield 42...",0,0,1,0,1,1,0
4,CEREALS,Rice,CR DHAN 810(IET 30409),Variety,"ICAR- National Rice Research Institute, Cuttac...",West Bengal,"Suitable forrainfed shallow low land, yield 42...",0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,Fruits,Velvet Bean,Arka Dhanvantari,OpenPollinated Variety,ICAR-Indian Institute of Horticultural Researc...,Karnataka,Long duration variety (180-190 days) with non-...,1,0,0,0,0,0,0
453,Fruits,Velvet Bean,Arka Daksha,OpenPollinated Variety,ICAR-Indian Institute of Horticultural Researc...,Karnataka,Medium duration variety comes to maturity 150-...,0,0,0,0,0,0,0
454,Fruits,Ashwagandha,Arka Ashwagandha,OpenPollinated Variety,ICAR-Indian Institute of Horticultural Researc...,Karnataka,It is pure line selection with high dry root y...,0,0,0,0,1,1,0
455,Fruits,Mandukaparni,Arka Prabhavi,OpenPollinated Variety,ICAR-Indian Institute of Horticultural Researc...,Karnataka,It produces 13 tonnes of fresh herb and 2.3 to...,0,0,0,0,0,0,0
456,Sr. No.,Crop,Name of the Variety/Hybrid,Variety/ Hybrid,Sponsoring organization,Recommended for the states,Special Features,0,0,0,0,0,0,0

In [32]:
def recommend_seed(crop, state, drought=0, rainfed=0, saline=0):
    
    filtered = df[
        (df["Crop"].str.lower()==crop.lower()) &
        (df["State"].str.lower()==state.lower())
    ].copy()
    
    filtered["score"] = (
        filtered["drought"]*drought +
        filtered["rainfed"]*rainfed +
        filtered["saline"]*saline +
        filtered["high_yield"]
    )
    
    filtered = filtered.sort_values("score", ascending=False)
    
    return filtered[["Name of Variety","score"]].head(3)

In [33]:
recommend_seed(
    crop="rice",
    state="maharashtra",
    drought=1,
    rainfed=1
)

            Name of Variety  score
19  DRR Dhan 74 (IET 30252)      1
1   CR Dhan 416 (IET 30201)      0

In [34]:
df.to_csv("../data/processed/seed_varieties_final_with_features.csv", index=False)

In [35]:
df

,Category,Crop,Name of Variety,Variety/Hybrid,Sponsoring organization,State,Description,drought,saline,rainfed,irrigated,disease_resistant,early_maturity,high_yield
0,CEREALS,Rice,CR Dhan 416 (IET 30201),Variety,"ICAR-National Rice Research Institute,Cuttack,...",West Bengal,"Suitable forcoastal saline areas,yield 48.97 q...",0,1,0,0,1,0,0
1,CEREALS,Rice,CR Dhan 416 (IET 30201),Variety,"ICAR-National Rice Research Institute,Cuttack,...",Maharashtra,"Suitable forcoastal saline areas,yield 48.97 q...",0,1,0,0,1,0,0
2,CEREALS,Rice,CR Dhan 416 (IET 30201),Variety,"ICAR-National Rice Research Institute,Cuttack,...",Gujarat,"Suitable forcoastal saline areas,yield 48.97 q...",0,1,0,0,1,0,0
3,CEREALS,Rice,CR DHAN 810(IET 30409),Variety,"ICAR- National Rice Research Institute, Cuttac...",Odisha,"Suitable forrainfed shallow low land, yield 42...",0,0,1,0,1,1,0
4,CEREALS,Rice,CR DHAN 810(IET 30409),Variety,"ICAR- National Rice Research Institute, Cuttac...",West Bengal,"Suitable forrainfed shallow low land, yield 42...",0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,Fruits,Velvet Bean,Arka Dhanvantari,OpenPollinated Variety,ICAR-Indian Institute of Horticultural Researc...,Karnataka,Long duration variety (180-190 days) with non-...,1,0,0,0,0,0,0
453,Fruits,Velvet Bean,Arka Daksha,OpenPollinated Variety,ICAR-Indian Institute of Horticultural Researc...,Karnataka,Medium duration variety comes to maturity 150-...,0,0,0,0,0,0,0
454,Fruits,Ashwagandha,Arka Ashwagandha,OpenPollinated Variety,ICAR-Indian Institute of Horticultural Researc...,Karnataka,It is pure line selection with high dry root y...,0,0,0,0,1,1,0
455,Fruits,Mandukaparni,Arka Prabhavi,OpenPollinated Variety,ICAR-Indian Institute of Horticultural Researc...,Karnataka,It produces 13 tonnes of fresh herb and 2.3 to...,0,0,0,0,0,0,0
456,Sr. No.,Crop,Name of the Variety/Hybrid,Variety/ Hybrid,Sponsoring organization,Recommended for the states,Special Features,0,0,0,0,0,0,0

In [36]:
mapping = {
"rice": ["DRR Dhan 74","CR Dhan 416","IR 64","MTU 1010","BPT 5204"],
"maize": ["HQPM 1","DHM 117","Vivek Hybrid 27","PMH 1"],
"blackgram": ["PU 31","LBG 752","VBN 8"],
"chickpea": ["JG 11","Pusa 372","ICCV 2"],
"kidneybeans": ["PDR 14","HUR 15","VL Rajma 125"],
"lentil": ["Pusa Vaibhav","PL 406","IPL 316"],
"mothbeans": ["RMO 40","CAZRI Moth 2","RMO 257"],
"mungbean": ["Pusa Vishal","SML 668","PDM 139"],
"pigeonpeas": ["ICPL 87119","Asha (ICPL 87119)","BSMR 736"],
"cotton": ["Bt Cotton RCH 2","Bunny Bt","NCS 855"],
"jute": ["JRO 524","JRO 8432","JRC 321"],
"coffee": ["Sln 795","Chandragiri","Selection 9"],
"coconut": ["West Coast Tall","Chowghat Orange Dwarf","Kalpa Sree"],
"banana": ["Grand Naine (G9)","Robusta","Dwarf Cavendish"],
"apple": ["Red Delicious","Golden Delicious","Granny Smith"],
"mango": ["Alphonso","Kesar","Dasheri"],
"orange": ["Nagpur Mandarin","Coorg Mandarin","Sathgudi"],
"papaya": ["Red Lady 786","Pusa Delicious","Coorg Honey Dew"],
"pomegranate": ["Bhagwa","Ganesh","Arakta"],
"grapes": ["Thompson Seedless","Bangalore Blue","Sonaka"],
"watermelon": ["Sugar Baby","Arka Jyoti","Charleston Gray"],
"muskmelon": ["Hara Madhu","Arka Jeet","Punjab Hybrid"]
}

In [37]:
new_rows = []

for crop, seeds in mapping.items():
    for seed in seeds:
        row = {}

        # keep all columns
        for col in df.columns:
            row[col] = None

        # fill required columns
        row["Crop"] = crop
        row["Variety"] = seed

        new_rows.append(row)

new_df = pd.DataFrame(new_rows)

In [38]:
final_df = pd.concat([df, new_df], ignore_index=True)

final_df = final_df.drop_duplicates()

final_df.to_csv("../data/processed/seed_dataset_final_complete.csv", index=False)

print("Saved: seed_dataset_final_complete.csv")

Saved: seed_dataset_final_complete.csv

In [39]:
df.isnull().sum()

Category                    0
Crop                        0
Name of Variety             0
Variety/Hybrid             19
Sponsoring organization     0
State                       0
Description                 0
drought                     0
saline                      0
rainfed                     0
irrigated                   0
disease_resistant           0
early_maturity              0
high_yield                  0
dtype: int64

In [40]:
df["Variety/Hybrid"] = df["Variety/Hybrid"].fillna("Variety")

In [42]:
df.isnull().sum()

Category                   0
Crop                       0
Name of Variety            0
Variety/Hybrid             0
Sponsoring organization    0
State                      0
Description                0
drought                    0
saline                     0
rainfed                    0
irrigated                  0
disease_resistant          0
early_maturity             0
high_yield                 0
dtype: int64

In [43]:
df.to_csv("../data/processed/seed_dataset_final_complete.csv", index=False)